import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import cn from "classnames";
import Header from "@/components/Header";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "h-screen bg-gray-800 text-white",
          "flex"
        )}
      >
        <Header />
        <div className="flex-grow flex flex-col">
          <TopBar />
          <main className="flex-grow max-w-7xl mx-auto w-full p-10">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
